//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.26 at 02:05:59 PM BST 
//


package org.dcdroid.api;

import java.util.ArrayList;
import java.util.List;

public class Enum 
{
    protected List<Entry> entries;

    public Enum()
    {
    	entries = new ArrayList<Entry>();
    }

    public List<Entry> getEntries() 
    {
        return this.entries;
    }

    public void setEntries(ArrayList<Entry> entries)
    {
    	this.entries = entries;
    }
    
    public void addEntry(Entry entry)
    {
    	entries.add(entry);
    }
}
