//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.26 at 02:05:59 PM BST 
//


package org.dcdroid.api;

public class Property {

    protected Param param;
    protected Enum e;
    protected Range range;
    protected String name;
    protected String kind;
    protected String unit;
    protected String value;

    public Param getParam() {
        return param;
    }

    public void setParam(Param value) {
        this.param = value;
    }

    public Enum getEnum() {
        return e;
    }

    public void setEnum(Enum value) {
        this.e = value;
    }

    public Range getRange() {
        return range;
    }

    public void setRange(Range value) {
        this.range = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getKind() {
        return kind;
    }

    public void setKind(String value) {
        this.kind = value;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String value) {
        this.unit = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getRangeEnumValueAsString()
    {
    	String s = "";
    	if(kind.toLowerCase().equals("fixed"))
    	{
    		if (unit.equals("count") || unit.equals("label"))
    		{
    			return value;
    		}
    		else
    		{
    			return value + unit;
    		}
    	}

    	if(kind.toLowerCase().equals("range"))
    	{
    		if (unit.equals("count") || unit.equals("label"))
    		{
    			s = range.getFirst() + " - " + range.getLast();
    		}
    		else
    		{
    			s = range.getFirst() + unit + " - " + range.getLast() + unit;
    		}
    	}
    	else if(kind.toLowerCase().equals("enum"))
    	{
    		for(Entry entry : e.getEntries())
    		{
    			s += entry + unit + ", ";
    		}
    	}
    	s += " (" + value + ")";
    	return s;
    }
}
