//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.26 at 02:05:59 PM BST 
//


package org.dcdroid.api;

public class Range {

    protected String first;
    protected String last;

    public String getFirst() {
        return first;
    }

    public void setFirst(String value) {
        this.first = value;
    }

    public String getLast() {
        return last;
    }

    public void setLast(String value) {
        this.last = value;
    }

}
