//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.26 at 02:05:59 PM BST 
//


package org.dcdroid.api;

import java.util.ArrayList;
import java.util.List;

public class Realms 
{
    protected List<Realm> realms;

	public Realms()
	{
		realms = new ArrayList<Realm>();
	}


    public List<Realm> getRealms() 
    {
        return this.realms;
    }

    public void addRealm(Realm realm)
    {
    	realms.add(realm);
    }

    public void setRealms(List<Realm> realms)
    {
    	this.realms = realms;
    }
 
    public void print()
    {
		for(Realm realm : getRealms())
		{
			System.out.println("======= Realm =======");
			System.out.println("Name: " + realm.getName());
			System.out.println("HREF: " + realm.getHref());
			System.out.println("ID: " + realm.getId());
			System.out.println("State: " + realm.getState());
		}
    }
}
